export declare const TENANT_PERMISSIONS: {
    readonly 'orders.read': "View orders";
    readonly 'orders.create': "Create orders";
    readonly 'orders.update': "Update orders";
    readonly 'orders.update_status': "Update order status";
    readonly 'orders.cancel': "Cancel orders";
    readonly 'orders.view_timeline': "View order timeline";
    readonly 'orders.use_kanban': "Use operational kanban";
    readonly 'orders.use_kds': "Use kitchen display system";
    readonly 'catalog.read': "View catalog";
    readonly 'catalog.create': "Create catalog items";
    readonly 'catalog.update': "Update catalog items";
    readonly 'catalog.delete': "Delete catalog items";
    readonly 'catalog.publish': "Publish catalog items";
    readonly 'catalog.manage_products': "Manage catalog products";
    readonly 'catalog.manage_option_groups': "Manage catalog option groups";
    readonly 'catalog.bulk_edit': "Bulk edit catalog";
    readonly 'catalog.manage_complements': "Manage catalog complements";
    readonly 'catalog.manage_combos': "Manage catalog combos";
    readonly 'kds.use': "Use kitchen display";
    readonly 'kds.manage': "Manage KDS settings";
    readonly 'cash.read': "View cash sessions and movements";
    readonly 'cash.open': "Open cash register";
    readonly 'cash.close': "Close cash register";
    readonly 'cash.add_supply': "Add cash supply";
    readonly 'cash.add_withdrawal': "Add cash withdrawal";
    readonly 'cash.manage': "Manage all cash operations";
    readonly 'pos.read': "View POS sales";
    readonly 'pos.create_sale': "Create POS sale";
    readonly 'pos.apply_discount': "Apply manual discount on POS";
    readonly 'pos.waiter_mode': "Access simplified waiter mode";
    readonly 'pos.transfer_table': "Transfer orders between tables";
    readonly 'reports.read': "View all reports";
    readonly 'reports.view_costs': "View ingredient and product costs";
    readonly 'reports.view_margin': "View product profit margins";
    readonly 'reports.export': "Export reports";
    readonly 'goals.read': "View goals and performance metrics";
    readonly 'goals.create': "Create new goals";
    readonly 'goals.update': "Update existing goals";
    readonly 'goals.delete': "Delete goals";
    readonly 'crm.read': "View CRM and Customer data";
    readonly 'crm.manage_customers': "Manage customers";
    readonly 'crm.manage_coupons': "Manage coupons";
    readonly 'crm.manage_loyalty_cashback': "Manage loyalty and cashback config";
    readonly 'crm.apply_benefits': "Apply coupons or cashback at POS";
    readonly 'delivery.read': "View delivery info";
    readonly 'delivery.manage_drivers': "Manage delivery drivers";
    readonly 'delivery.dispatch': "Dispatch deliveries";
    readonly 'delivery.manage': "Manage delivery settings";
    readonly 'inventory.read': "View inventory and stock";
    readonly 'inventory.create': "Create inventory items";
    readonly 'inventory.update': "Update inventory items";
    readonly 'inventory.adjust': "Manual stock adjustments";
    readonly 'inventory.manage_recipe': "Manage product technical datasheets";
    readonly 'inventory.view_costs': "View ingredient and recipe costs";
    readonly 'inventory.view_margin': "View product profit margins";
    readonly 'finance.read': "View financial data";
    readonly 'finance.manage': "Manage financial data";
    readonly 'settings.read': "View settings";
    readonly 'settings.manage': "Manage settings";
    readonly 'users.read': "View users";
    readonly 'users.create': "Create users";
    readonly 'users.update': "Update users";
    readonly 'users.delete': "Delete users";
    readonly 'users.roles': "Manage user roles";
    readonly 'dashboard.view': "View dashboard";
    readonly 'billing.read': "View billing and plans";
    readonly 'billing.write': "Manage billing and subscriptions";
};
export type TenantPermission = keyof typeof TENANT_PERMISSIONS;
export declare const ADMIN_PERMISSIONS: {
    readonly 'saas.tenants.read': "View tenants";
    readonly 'saas.tenants.create': "Create tenants";
    readonly 'saas.tenants.update': "Update tenants";
    readonly 'saas.tenants.suspend': "Suspend tenants";
    readonly 'saas.plans.read': "View plans";
    readonly 'saas.plans.manage': "Manage plans";
    readonly 'saas.billing.read': "View billing";
    readonly 'saas.billing.manage': "Manage billing";
    readonly 'saas.support.access': "Access support tools";
    readonly 'saas.support.impersonate': "Impersonate tenant users";
    readonly 'saas.audit.read': "View audit logs";
    readonly 'saas.modules.manage': "Manage modules";
    readonly 'saas.metrics.read': "View platform metrics";
    readonly 'saas.users.read': "View admin users";
    readonly 'saas.users.manage': "Manage admin users";
    readonly 'saas.onboarding.manage': "Manage tenant onboarding";
    readonly 'saas.settings.read': "View system settings";
    readonly 'saas.settings.manage': "Manage system settings";
};
export type AdminPermission = keyof typeof ADMIN_PERMISSIONS;
export declare const TENANT_ROLE_PERMISSIONS: Record<string, TenantPermission[]>;
export declare const ADMIN_ROLE_PERMISSIONS: Record<string, AdminPermission[]>;
