services:
  # Backend API
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=CPNET_ATTACH"
      - "traefik.http.routers.gestor-api.rule=Host(`${API_DOMAIN:-api.kigula.dpdns.org}`)"
      - "traefik.http.routers.gestor-api.entrypoints=websecure"
      - "traefik.http.routers.gestor-api.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.gestor-api.service=gestor-api"
      - "traefik.http.services.gestor-api.loadbalancer.server.port=3333"
      - "traefik.http.services.gestor-api.loadbalancer.passHostHeader=true"
    env_file:
      - .env
    environment:
      DIRECT_URL: ${DIRECT_URL:-${DATABASE_URL}}
      NODE_ENV: production
      API_PORT: 3333
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_ENABLED: ${REDIS_ENABLED:-true}
    networks:
      - CPNET_ATTACH

networks:
  CPNET_ATTACH:
    external: true
    name: CPNET_ATTACH
