export interface AnalyticsPerformancePeriod { from: string; to: string; timezone: string; }
export interface AnalyticsMetricDelta { absolute: number; percentage: number | null; direction: 'up' | 'down' | 'flat'; }
export interface AnalyticsOverviewMetrics { sessions: number; menuViews: number; productViews: number; addToCart: number; checkoutStarted: number; ordersSubmitted: number; ordersConfirmed: number; ordersCompleted: number; ordersCancelled: number; storefrontConversionRate: number; acceptanceRate: number; completionRate: number; realizedRevenue: number; averageOrderValue: number; currency: 'BRL'; }
export interface AnalyticsOverviewResponse { period: AnalyticsPerformancePeriod; current: AnalyticsOverviewMetrics; previous: AnalyticsOverviewMetrics | null; delta: Record<string, AnalyticsMetricDelta> | null; }
export interface AnalyticsFunnelStep { eventName: 'menu_viewed' | 'product_viewed' | 'add_to_cart' | 'checkout_started' | 'order_submitted' | 'order_completed'; eventCount: number; uniqueSessions: number; conversionFromPrevious: number; conversionFromStart: number; dropOffFromPrevious: number; }
export interface AnalyticsFunnelResponse { period: AnalyticsPerformancePeriod; current: AnalyticsFunnelStep[]; previous: AnalyticsFunnelStep[] | null; delta: Array<{ eventName: string; eventCount: AnalyticsMetricDelta; uniqueSessions: AnalyticsMetricDelta }> | null; }
export interface AnalyticsProductPerformance { productId: string; productName: string; categoryId: string | null; categoryName: string | null; views: number; selections: number; addToCart: number; ordersSubmitted: number; ordersCompleted: number; quantityCompleted: number; realizedRevenue: number; viewToCartRate: number; cartToOrderRate: number; currency: 'BRL'; }
export interface AnalyticsProductsPage { items: AnalyticsProductPerformance[]; page: number; limit: number; total: number; }
export interface AnalyticsProductsResponse { period: AnalyticsPerformancePeriod; current: AnalyticsProductsPage; previous: AnalyticsProductsPage | null; delta: Array<{ id: string; realizedRevenue: AnalyticsMetricDelta }> | null; }
export interface AnalyticsAcquisitionCoverage { attributionStatus: 'partial'; coverage: 'utm_tagged_only'; directUnknownAvailable: false; revenueAttributionAvailable: false; }
export interface AnalyticsAcquisitionRow { dimensionType: 'utm_source' | 'utm_medium' | 'utm_campaign'; dimensionKey: string; sessions: number; menuViews: number; ordersSubmitted: number; ordersCompleted: number; conversionRate: number; realizedRevenue: null; }
export interface AnalyticsAcquisitionPage { items: AnalyticsAcquisitionRow[]; page: number; limit: number; total: number; }
export interface AnalyticsAcquisitionResponse { period: AnalyticsPerformancePeriod; attribution: AnalyticsAcquisitionCoverage; current: AnalyticsAcquisitionPage; previous: AnalyticsAcquisitionPage | null; delta: Array<{ id: string; realizedRevenue: AnalyticsMetricDelta }> | null; }
