import type { ComponentType, ReactNode, SVGProps } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, ArrowRight, Banknote, CheckCircle2, ChefHat, ExternalLink, PackageCheck, ReceiptText, ShoppingBag, Store, UtensilsCrossed, XCircle } from 'lucide-react';
import type { DashboardStatsDTO } from '@gestor/types';
import { getOperationalSteps, type StoreOperationalStatus } from '../dashboard.utils';

type Icon = ComponentType<SVGProps<SVGSVGElement>>;
type Props = { current: DashboardStatsDTO | null; storeStatus: StoreOperationalStatus; tenantSlug?: string; tenantName?: string; billingWarning?: string | null; analyticsAvailable: boolean; canOpenReports: boolean; onCopyMenu: () => void };

const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const number = (value: number) => value.toLocaleString('pt-BR');
const statusCopy: Record<StoreOperationalStatus, { label: string; detail: string; tone: string }> = {
  open: { label: 'Loja aberta', detail: 'Recebendo pedidos agora', tone: 'bg-emerald-500' },
  paused: { label: 'Operação pausada', detail: 'Pedidos temporariamente suspensos', tone: 'bg-amber-500' },
  closed: { label: 'Loja fechada', detail: 'Fora do horário configurado', tone: 'bg-rose-500' },
};
const flowTone: Record<string, string> = { sky: 'bg-sky-500', amber: 'bg-amber-500', indigo: 'bg-indigo-500', emerald: 'bg-emerald-500', slate: 'bg-slate-500' };

function Panel({ title, subtitle, children }: { title: string; subtitle?: string; children: ReactNode }) {
  return <section className="min-w-0 rounded-2xl border border-border bg-card shadow-card"><header className="border-b border-border px-4 py-3.5"><h2 className="text-sm font-bold tracking-tight text-foreground">{title}</h2>{subtitle ? <p className="mt-0.5 text-[11px] text-muted-foreground">{subtitle}</p> : null}</header>{children}</section>;
}

function QuickActions({ tenantSlug, tenantName, onCopyMenu }: Pick<Props, 'tenantSlug' | 'tenantName' | 'onCopyMenu'>) {
  const actions: Array<{ to: string; label: string; icon: Icon }> = [
    { to: '/orders', label: 'Pedidos', icon: ShoppingBag }, { to: '/cash', label: 'Caixa', icon: Banknote },
    { to: '/catalog/products', label: 'Produtos', icon: PackageCheck }, { to: '/settings', label: 'Ajustes', icon: Store },
  ];
  return <Panel title="Ações rápidas" subtitle={tenantName ? `Atalhos de ${tenantName}` : 'Atalhos da operação'}><nav className="grid grid-cols-2 gap-2 p-4" aria-label="Ações rápidas">{actions.map(({ to, label, icon: ItemIcon }) => <Link key={to} to={to} className="flex min-w-0 items-center gap-2 rounded-lg border border-border bg-secondary/40 px-3 py-2 text-xs font-semibold hover:border-primary/40 focus:outline-none focus:ring-2 focus:ring-ring"><ItemIcon className="h-3.5 w-3.5 shrink-0 text-primary" /><span className="truncate">{label}</span></Link>)}{tenantSlug ? <button type="button" onClick={onCopyMenu} className="col-span-2 flex items-center justify-center gap-2 rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:border-primary/40 focus:outline-none focus:ring-2 focus:ring-ring"><ExternalLink className="h-3.5 w-3.5" />Compartilhar cardápio</button> : null}</nav></Panel>;
}

function Kpi({ icon: Icon, label, value, hint }: { icon: Icon; label: string; value: string; hint?: string }) {
  return <article className="min-w-0 rounded-xl border border-border bg-card px-4 py-3.5 shadow-card"><div className="flex items-center justify-between gap-2"><span className="text-xs font-semibold text-muted-foreground">{label}</span><span className="rounded-lg border border-border bg-secondary p-1.5 text-muted-foreground"><Icon className="h-3.5 w-3.5" aria-hidden="true" /></span></div><p className="mt-2 truncate text-xl font-bold tabular-nums tracking-tight text-foreground">{value}</p>{hint ? <p className="mt-1 text-[11px] text-muted-foreground">{hint}</p> : null}</article>;
}

export function OperationsDashboard({ current, storeStatus, tenantSlug, tenantName, billingWarning, analyticsAvailable, canOpenReports, onCopyMenu }: Props) {
  const status = statusCopy[storeStatus];
  const pending = current?.operational.ordersByStatus.pending ?? 0;
  const flow = getOperationalSteps(current);
  const completedOrders = current?.commercial.totalOrders ?? 0;
  const completedRevenue = current?.commercial.totalRevenue ?? 0;
  const averageTicket = current?.commercial.averageTicket ?? 0;
  const cancellationRate = current?.operational.cancellationRate ?? 0;
  const preparing = flow.find((item) => item.key === 'preparing')?.count ?? 0;
  const ready = flow.find((item) => item.key === 'ready')?.count ?? 0;
  const deliveryOrders = current?.operational.ordersByFulfillment.delivery ?? 0;

  return <div className="space-y-4">
    {billingWarning ? <div className="flex flex-wrap items-start gap-3 rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-800 dark:text-amber-200"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" /><p className="min-w-0 flex-1">{billingWarning}</p><Link to="/billing" className="shrink-0 font-semibold underline-offset-4 hover:underline">Ver financeiro</Link></div> : null}

    <section aria-label="Pulso da operação" className="rounded-2xl border border-slate-200 bg-white px-4 py-4 text-slate-900 shadow-card dark:border-slate-800 dark:bg-slate-900 dark:text-slate-100 sm:px-5"><div className="grid items-center gap-4 lg:grid-cols-[1.2fr_auto_1fr]"><div className="flex min-w-0 items-center gap-3"><span className="relative flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 dark:border-slate-700 dark:bg-slate-800"><Store className="h-5 w-5 text-slate-700 dark:text-slate-200" aria-hidden="true" /><span className={`absolute -right-1 -top-1 h-2.5 w-2.5 rounded-full border-2 border-white dark:border-slate-900 ${status.tone}`} /></span><div className="min-w-0"><p className="truncate text-sm font-bold">{status.label}</p><p className="truncate text-xs text-slate-600 dark:text-slate-400">{status.detail}</p></div></div><div className="hidden h-9 w-px bg-slate-200 dark:bg-slate-700 lg:block" /><div className="grid grid-cols-2 gap-3">{analyticsAvailable ? <div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-500 dark:text-slate-400">Atenção</p><p className={`mt-1 text-base font-bold tabular-nums ${pending > 0 ? 'text-amber-700 dark:text-amber-300' : 'text-emerald-700 dark:text-emerald-300'}`}>{pending} <span className="text-xs font-medium text-slate-600 dark:text-slate-400">aguardando</span></p></div> : <p className="text-xs leading-relaxed text-slate-600 dark:text-slate-400">Acompanhe pedidos, caixa e ajustes da sua operação.</p>}<Link to={storeStatus === 'open' ? '/orders' : '/settings'} className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold transition hover:border-indigo-400 hover:bg-indigo-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 dark:border-slate-700 dark:bg-slate-800 dark:hover:bg-indigo-500/15 dark:focus:ring-indigo-400 dark:focus:ring-offset-slate-900">{analyticsAvailable && pending > 0 ? 'Ver fila' : storeStatus === 'open' ? 'Ver pedidos' : 'Ajustar operação'}<ArrowRight className="h-3.5 w-3.5" /></Link></div></div></section>

    {!analyticsAvailable ? <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card px-5 py-5 shadow-card"><h2 className="text-sm font-bold text-foreground">Painel operacional disponível</h2><p className="mt-1 text-xs leading-relaxed text-muted-foreground">O acompanhamento de vendas e métricas depende da permissão de Relatórios. Seus atalhos operacionais continuam disponíveis.</p><Link to="/orders" className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-primary hover:underline">Abrir pedidos <ArrowRight className="h-3.5 w-3.5" /></Link></section><QuickActions tenantSlug={tenantSlug} tenantName={tenantName} onCopyMenu={onCopyMenu} /></div> : <>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Kpi label="Vendas concluídas" value={money(completedRevenue)} hint="Valor dos pedidos concluídos" icon={Banknote} /><Kpi label="Pedidos concluídos" value={number(completedOrders)} icon={ShoppingBag} /><Kpi label="Ticket médio" value={money(averageTicket)} hint="Vendas concluídas ÷ pedidos concluídos" icon={ReceiptText} /><Kpi label="Cancelamentos" value={`${cancellationRate.toFixed(1)}%`} icon={XCircle} /></div>
      <div className="grid gap-4 xl:grid-cols-[1.55fr_0.85fr]"><Panel title="Fluxo operacional" subtitle="Pedidos que precisam avançar hoje"><div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-3 lg:grid-cols-6">{flow.map((step) => <Link key={step.key} to="/orders" className="group bg-card px-3 py-4 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-ring"><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-semibold text-muted-foreground">{step.label}</span><ArrowRight className="h-3 w-3 text-muted-foreground opacity-0 transition group-hover:opacity-100" /></div><p className="mt-2 text-xl font-bold tabular-nums text-foreground">{step.count}</p><div className="mt-2 h-1 overflow-hidden rounded bg-secondary"><div className={`h-full rounded ${flowTone[step.tone]}`} style={{ width: `${step.share}%` }} /></div></Link>)}</div></Panel><Panel title="Pontos de atenção" subtitle="Somente condições que pedem ação"><div className="divide-y divide-border px-4">{pending > 0 ? <Link to="/orders" className="flex items-center gap-3 py-3.5"><span className="rounded-lg bg-amber-500/10 p-2 text-amber-600"><AlertTriangle className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-xs font-bold text-foreground">{pending} pedido{pending === 1 ? '' : 's'} aguardando aceite</p><p className="text-[11px] text-muted-foreground">Revise a fila de entrada.</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link> : null}{storeStatus !== 'open' ? <Link to="/settings" className="flex items-center gap-3 py-3.5"><span className="rounded-lg bg-rose-500/10 p-2 text-rose-600"><Store className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-xs font-bold text-foreground">{status.label}</p><p className="text-[11px] text-muted-foreground">{status.detail}.</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link> : null}{pending === 0 && storeStatus === 'open' ? <div className="flex items-center gap-3 py-5"><span className="rounded-lg bg-emerald-500/10 p-2 text-emerald-600"><CheckCircle2 className="h-4 w-4" /></span><div><p className="text-xs font-bold text-foreground">Operação em dia</p><p className="text-[11px] text-muted-foreground">Nenhuma ação imediata identificada.</p></div></div> : null}</div></Panel></div>
      <div className="grid gap-4 lg:grid-cols-2"><Panel title="Cozinha" subtitle="Situação atual dos pedidos"><div className="grid grid-cols-3 gap-3 p-4"><div className="rounded-xl bg-secondary/60 p-3"><ChefHat className="h-4 w-4 text-indigo-500" /><p className="mt-3 text-xl font-bold tabular-nums">{preparing}</p><p className="text-[11px] text-muted-foreground">Na cozinha</p></div><div className="rounded-xl bg-secondary/60 p-3"><UtensilsCrossed className="h-4 w-4 text-amber-500" /><p className="mt-3 text-xl font-bold tabular-nums">{ready}</p><p className="text-[11px] text-muted-foreground">Prontos</p></div><div className="rounded-xl bg-secondary/60 p-3"><ShoppingBag className="h-4 w-4 text-sky-500" /><p className="mt-3 text-xl font-bold tabular-nums">{deliveryOrders}</p><p className="text-[11px] text-muted-foreground">Em entrega</p></div></div></Panel><QuickActions tenantSlug={tenantSlug} tenantName={tenantName} onCopyMenu={onCopyMenu} /></div>
      {canOpenReports ? <Link to="/analytics/reports" className="flex items-center justify-between rounded-xl border border-border bg-card px-4 py-3 text-sm font-semibold text-foreground shadow-card transition hover:border-primary/40 focus:outline-none focus:ring-2 focus:ring-ring"><span><span className="block">Quer analisar o desempenho?</span><span className="mt-0.5 block text-[11px] font-normal text-muted-foreground">Veja canais, produtos e períodos em Relatórios.</span></span><span className="inline-flex shrink-0 items-center gap-1 text-xs text-primary">Ver relatórios <ArrowRight className="h-3.5 w-3.5" /></span></Link> : null}
    </>}
  </div>;
}
